version: "2"

services:
  bedrock:
    volumes:
      - .certs:/etc/nginx/certs
      - ./bedrock:/var/www # will be mounted on /var/www
      - ./templates:/var/templates # will be mounted on /var/templates
    env_file:
      - .docker/stages/dev/env/db.development.env
      - .docker/stages/dev/env/bedrock.development.env

  db:
    env_file: .docker/stages/dev/env/db.development.env
    ports:
      - "3306:3306"

  phpmyadmin:
    env_file: .docker/stages/dev/env/db.development.env
