source 'https://rubygems.org'

gem 'capistrano'
gem 'capistrano-composer'
gem 'airbrussh', :require => false
# gem 'capistrano-npm'
gem 'capistrano-git-submodule-strategy', '~> 0.1', :github => 'ekho/capistrano-git-submodule-strategy'